### ISSUE TITLE
unable to decrypt the sender device has not sent us the key for this message

### ISSUE THREAD

**Issue by syrakozz** [ppulwey/matrix-expo#1]
plz help im getting unable to decrypt the sender device has not sent us the key for this message

**Comment by lauti7** [comment]
stuck in this too. did you figure out the issue?

**Comment by lauti7** [comment]
> plz help im getting unable to decrypt the sender device has not sent us the key for this message

@syrakozz

**Comment by ppulwey** [comment]
This wan an example how to get matrix running in an expo app and it may be out of date. Nevertheless, I never get it running correctly.
See my issue in the official JS SDK: https://github.com/matrix-org/matrix-js-sdk/issues/1800
